keycloak:
  image:
    tag: 16.1.1-debian-10-r103
  auth:
    adminUser: admin
    existingSecret: sharedidp-keycloak
  proxyAddressForwarding: true
  serviceDiscovery:
    enabled: true
  extraEnvVars:
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sharedidp-keycloak
          key: admin-password
    - name: CACHE_OWNERS_COUNT
      value: "3"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "3"
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
  replicaCount: 3
  extraVolumes:
    - name: themes-catenax-shared
      emptyDir: {}
    - name: themes-catenax-shared-portal
      emptyDir: {}
    - name: realms
      emptyDir: {}
  extraVolumeMounts:
    - name: themes-catenax-shared
      mountPath: "/opt/bitnami/keycloak/themes/catenax-shared"
    - name: themes-catenax-shared-portal
      mountPath: "/opt/bitnami/keycloak/themes/catenax-shared-portal"
    - name: realms
      mountPath: "/realms"
  initContainers:
    - name: import
      image: ghcr.io/catenax-ng/product-portal-iam_iam-import:v0.5.3
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes-catenax-shared..."
          cp -R /import/themes/catenax-shared/* /themes-catenax-shared
          echo "Copying themes-catenax-shared-portal..."
          cp -R /import/themes/catenax-shared-portal/* /themes-catenax-shared-portal
          echo "Copying realms..."
          cp -R /import/catenax-shared/realms/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
  service:
    type: ClusterIP
    sessionAffinity: ClientIP
  ingress:
    enabled: false
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
  postgresql:
    enabled: true
    auth:
      username: kcshared
      database: iamsharedidp
      existingSecret: sharedidp-postgres
    architecture: replication

secrets:
  auth:
    existingSecret:
      adminpassword: ""
      managementpassword: ""
  postgresql:
    auth:
      existingSecret:
        postgrespassword: ""
        password: ""
        replicationPassword: ""
  realmuser:
    enabled: false
