apiVersion: v1
data:
  azurestorageaccountkey: WlIra3d6V0xDRVIzOTUzWkhKOGVmc291UmpPeEZSQm5kQ2ZPSjliQmxQSlV0bVRvRFBHTGhnd1ZXKzF0Q2JEaFltSklaaGdhekVuWng4TGtNcFNoc3c9PQ==
  azurestorageaccountname: Y2F0ZW5heGRldjAwM3V0aWw=
kind: Secret
metadata:
  name: iam-storage-secret
  namespace: helm
type: Opaque