apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.extraVolumeSecretPath }}
  name: secret-centralidp-realms
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CX-Central-users-0.json: <CX-Central-users-0.json>