apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.auth.secret.path }}
  name: {{ .Values.auth.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-password: <admin-password>
  management-password: <management-password>