apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.auth.existingSecretPath }}
  name: sharedidp-keycloak
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-password: <admin-password>
  management-password: <management-password>