apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.secrets.extraVolumes.secret.path }}
  name: secret-sharedidp-realms
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  master-realm-users-0.json: <master-realm-users-0.json>
  CX-Test-Access-users-0.json: <CX-Test-Access-users-0.json>
  Company-1-users-0.json: <Company-1-users-0.json>
  Company-2-users-0.json: <Company-2-users-0.json>
  Company-3-users-0.json: <Company-3-users-0.json>