apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.postgresql.secret.path }}
  name: {{ .Values.postgresql.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres-password: <postgres-password>
  password: <password>
  replication-password: <replication-password>