apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.secrets.auth.existingSecret.path }}
  name: sharedidp-keycloak
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-password: <admin-password>
  management-password: <management-password>